apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistent-ping-log-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistent-ping-log-app
  template:
    metadata:
      labels:
        app: persistent-ping-log-app
    spec:
      containers:
        - name: ping-pong-service # ping pong write only
          image: mmiglioranza22/k8s-ex.1.11-ping-pong-service
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: logger-service # logger writes/reads and GETS
          image: mmiglioranza22/k8s-ex.1.11-logger-service
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-logs-claim
#
# App: persistent-ping-log-app
# Service 1 (write): write-log-service
# Service 2 (read): read-log-service
# An app can contain containers that perform different tasks (read, write, etc).
# The important port to expose/target is the read app (the one that can be accesed via GET)

