apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-app
  ports:
    - name: ping-pong
      port: 3000
      protocol: TCP
      targetPort: 3000 # The app's exposed port (defined 3000 in the source code)

# GKE is used without an Ingress for this particular app
# You need the loadbalance external api with kubectl get svc [--watch] and add the port opened for it, and request to the specific resouce path/route
#
# NAME            TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)          AGE
# kubernetes      ClusterIP      34.118.224.1     <none>         443/TCP          33m
# ping-pong-svc   LoadBalancer   34.118.237.145   35.184.158.3   3000:30172/TCP   27m
# postgres-svc    ClusterIP      None             <none>         5432/TCP         27m
#
# curl http://35.184.158.3:3000/pingpong
