apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-stset
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db-container
          image: postgres
          # envFrom:
          #   - configMapRef:
          #       name: postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            - name: postgres-database
              mountPath: /usr/src/app/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-database # same as volumeMount.name
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName: local-path # this is managed directly by GKE, no need for PVClaims too -> https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes
        resources:
          requests:
            storage: 100Mi
