apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hashgenerator2-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hashgenerator2-svc
                port:
                  number: 2345 # points to the port assigned to the ClusterIp service (this is inside the cluster)
