apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: mmiglioranza22/project-todo-app
          env:
            - name: ENV_VAR
              value: "This is the ENV_VAR value: Hello!"
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
