apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc
  namespace: todo-app-ns
spec:
  type: ClusterIP
  selector:
    app: todo-app-backend
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 5555 # todo-backend port
