apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: todo-app-ns
spec:
  ########## ┌───────────── minute (0 - 59)
  ########## │ ┌───────────── hour (0 - 23)
  ########## │ │ ┌───────────── day of the month (1 - 31)
  ########## │ │ │ ┌───────────── month (1 - 12)
  ########## │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
  ########## │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
  ########## │ │ │ │ │
  ########## │ │ │ │ │
  ########## * * * * *
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-todo
              image: mmiglioranza22/k8s-ex.2.09-cronjob-todo-curl
              env:
                - name: INTERNAL_BACKEND_URL
                  value: http://todo-app-backend-svc:1234/api/todos # ALWAYS THE SERVICE-NAME:PORT
          restartPolicy: OnFailure
