apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app-ns
resources:
  - ./namespace.yaml
  - ./front-deployment.yaml
  - ./front-service.yaml
  - ./back-deployment.yaml
  - ./back-service.yaml
  - ./statefulset.yaml
  - ./statefulset-service.yaml
  - ./ingress.yaml
  - ./configmap.yaml
  - ./secret.yaml
  - ./cronjob.yaml
  - ./debugging.yaml
images:
  - name: FRONT_IMAGE
    newName: mmiglioranza22/project-todo-app-frontend
  - name: BACK_IMAGE
    newName: mmiglioranza22/project-todo-app-backend
  - name: DB_IMAGE
    newName: postgres
  - name: CRON_IMAGE
    newName: mmiglioranza22/k8s-ex.2.09-cronjob-curl-script
  - name: DEBUG_IMAGE
    newName: busybox
