# This file is securely encypted and can be pushed to remote
# To decrypt it using SOPS, 2 ways:
# Creating a plain secret file (not recomended)
#
#   export SOPS_AGE_KEY_FILE=$(pwd)/key.txt (path to your key file)
#   sops --decrypt secret.enc.yaml > secret.dec.yaml
#
# Or piping the secret directly to kubectl (we are running the cluster locally):
#
#   sops --decrypt secret.enc.yaml | kubectl apply -f -
#
apiVersion: v1
kind: Secret
metadata:
  name: ping-pong-apikey
data:
  API_KEY: ENC[AES256_GCM,data:PEG216wo+W43fIEHAcKWFu47987RrYv5XpYCWhEjrLRm,iv:TXbPafNIs9sgJDhNCVLW6omjstVxj4eKxArrXlZi24g=,tag:6QvOrey1yOdKdI0lniHE+w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1529d7ycqn480mj37xf8ydtpmyyhzazlx752hfdejwdgekc6vaedsj3dtpp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbTB1N2RYUCtBcXREWmRX
        TWJIbFJYbXYvd01MWkhFRW91S3BiYnBGZW13CjBxc01sbEtTMjdzNmlaNy82N2Rm
        Q2pLNGF4Y1VNc0NON2VEQnZvZGZNWncKLS0tIFRybkhEYzI0Si9Zck40d2JiQ1Mw
        UjJHUGk5bVNzZDVrbTh5YVM3ZUhKTWMKJXbl2T2giuYfpI7wvr9VIFyEtYMexFc6
        NxgDGReDnxhciUfGIqYfUHCGHo1dVYyOOCokMGaHGgscDP47Hnvkgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-11T15:14:44Z"
  mac: ENC[AES256_GCM,data:GmVMrv/fXTUPM02kDvwuCN7MCuBy0Y/sYD6LmzUZuf+JL5cbz8BEmMiWqpIulg81DQ9xNSZzJ10f53ePWFfd1gHCBkywsqg5A0L2oTZA6/p3tipLqLEWlQFAS0Dpxvm7KH5/HWC0XWQw5kyfzebmTVwMCbs3Qh6Jj6h/uVf5ULY=,iv:F5n69bQxBpyVpD0/iB9yCAizs/Rn4ZQPIgBATKkDOwg=,tag:gTy6qax9KHRux1Tn/poV2A==,type:str]
  pgp: []
  encrypted_regex: ^(data)$
  version: 3.9.0
