apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres-svc" # host points to the service running the postgres image connection (stateful set)
  POSTGRES_PORT: "5432"
