apiVersion: v1
kind: Pod
metadata:
  name: ping-pong-app-pod
spec:
  containers:
    - name: ping-pong-app
      image: mmiglioranza22/k8s-ex.2.08-ping-pong-service
      envFrom:
        - configMapRef:
            name: postgres-config
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
      # ports:
      # - containerPort: 3000
