apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-stset
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db-container
          image: postgres
          # envFrom:
          #   - configMapRef:
          #       name: postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            - name: postgres-database
              mountPath: /usr/src/app/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-database # same as volumeMount.name
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres-db # the chosen container name
spec:
  ports:
    - port: 5432
      name: db

  clusterIP: None # this is necessary to ensure pods identity stays the same (for network and name)
  selector:
    app: postgres-db
