apiVersion: v1
kind: Service
metadata:
  name: read-write-app-svc
spec:
  type: ClusterIP
  selector:
    app: read-write-app
  ports:
    - port: 5151 # self. Inner port available within the cluster
      protocol: TCP
      targetPort: 3000 # The app's exposed port (defined 3000 in the source code) -> read-log-service
