apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 5555 # self. Inner port available within the cluster
      protocol: TCP
      targetPort: 8080 # The app's exposed port (defined 8080 in the source code)
